services:
  flask_app:
    container_name: climapuc
    build:
      context: .  # Diretório atual
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Porta 80 do host mapeada para o container
    volumes:
      - .:/app  # Monta o diretório local no container
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - MQTT_BROKER=192.168.1.110  # Certifique-se de usar variáveis para flexibilidade
    command: gunicorn -w 4 --reload -b 0.0.0.0:80 src.app:app
    depends_on:
      - mysql
      - mqtt_handler  # Garante que o serviço MQTT seja iniciado antes, se necessário

  mqtt_handler:
    build:
      context: .  # Pode ser o mesmo contexto se as dependências forem iguais
      dockerfile: Dockerfile  # Se necessário, você pode criar um Dockerfile específico para o MQTT
    container_name: mqtt_handler
    volumes:
      - .:/app
    environment:
      - MQTT_BROKER=BrokerEstacao
    command: python mqtt_handler.py  # Ou python mqtt_setup.py, conforme o nome do seu script
  
  # Container do script de monitoramento
  mqtt_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt_monitor
    command: /monitor.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite controlar o Docker de dentro do container
    depends_on:
      - mqtt_handler

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: weather_data
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tabela.sql:/docker-entrypoint-initdb.d/tabela.sql
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminN 
    environment:
      PMA_HOST: mysql  # Nome do serviço MySQL no Docker Compose
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example  # Deve ser igual ao configurado no MySQL
    ports:
      - "8000:80"  # Porta para acessar o phpMyAdmin no navegador
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
